name: Run Tests

on: [pull_request]

jobs:
  qc:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: php:8.5-cli-alpine
    steps:
      - name: Install system dependencies
        run: apk -q add git nodejs

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore cached vendor directory
        uses: actions/cache@v4
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: php composer.phar install -qo

      - name: Run Mago lint
        run: ./vendor/bin/mago lint

      - name: Run Mago analyze
        run: ./vendor/bin/mago analyze

  test:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4', '8.5']
        weasyprint-version: ['67.0', '68.0', '69.0']
        composer-flags: ['']
        include:
          - php-version: '8.3'
            weasyprint-version: '67.0'
            composer-flags: '--prefer-lowest --prefer-stable'
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php-version }}-cli-alpine
    steps:
      - name: Install system dependencies
        run: apk -q add git nodejs py3-pip py3-pillow py3-cffi py3-brotli gcc musl-dev python3-dev pango fontconfig-dev font-noto

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore cached vendor directory
        if: matrix.composer-flags == ''
        uses: actions/cache@v4
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: |
          if [ -n "${{ matrix.composer-flags }}" ]; then
            php composer.phar update -qo ${{ matrix.composer-flags }}
          else
            php composer.phar install -qo
          fi

      - name: Install and verify WeasyPrint
        run: pip3 -q install weasyprint==${{ matrix.weasyprint-version }} --break-system-packages && weasyprint --info

      - name: Run tests
        run: ./vendor/bin/pest --profile
